name: Build
run-name: Build and deploy by @${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  docker:
    if: github.repository == 'CytonicMC/CytonicBedwars'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Assemble Jar
        run: ./gradlew --no-daemon assemble

      - name: Login to GHCR
        run: echo $GHCR_TOKEN | docker login ghcr.io -u CytonicMC --password-stdin
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker Image for multiple platforms
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/cytonicmc/cytonic_bedwars:latest -f docker/Dockerfile . --push
